import { IssueSet, IssueSpec, SEV_MEDIUM } from '../../src/ncdb/index.js';

describe('IssueSet compatibility', () => {
  test('full round-trip preserves fields', () => {
    const issues = new IssueSet();
    issues.addIssue(new IssueSpec({
      id: 'I-001',
      ext: 'EXT-1',
      severity: 3,
      kind: 1,
      state: 2,
      resolution: 1,
      createdAt: 1700000000,
      updatedAt: 1700000001,
      syncedAt: 42,
    }));

    const roundTrip = IssueSet.fromBytes(issues.serialize());
    const handle = roundTrip.get('I-001');
    expect(handle).not.toBeNull();
    expect(handle?.ext).toBe('EXT-1');
    expect(handle?.severity).toBe(3);
    expect(handle?.kind).toBe(1);
    expect(handle?.state).toBe(2);
    expect(handle?.resolution).toBe(1);
    expect(handle?.createdAt).toBe(1700000000);
    expect(handle?.updatedAt).toBe(1700000001);
    expect(handle?.syncedAt).toBe(42);
  });

  test('matches Python-generated bytes', () => {
    const issues = new IssueSet();
    issues.addIssue(new IssueSpec({
      id: 'I-001',
      ext: '',
      severity: SEV_MEDIUM,
      kind: 0,
      state: 0,
      resolution: 0,
      createdAt: 1700000000,
      updatedAt: 1700000001,
      syncedAt: 0,
    }));

    expect(Buffer.from(issues.serialize()).toString('hex')).toBe(
      '42535349010000000001000000000000000000000000000000020005492d30303101000000004000f1536501f1536500000000',
    );
  });
});
