"""The published C++ reference is extracted, and extraction still works.

The API reference is generated by Hawkmoth from
``cpp/ucis-xml/include/ucis_xml.hpp``, so it cannot drift from the shipped
header the way a hand-written page does. What it *can* do is silently stop
extracting -- a renamed symbol, a comment demoted from ``/**`` to ``//``, a
toolchain change -- and the failure mode is a page that builds cleanly with
things missing from it. That is what this file is for.

Three properties are checked:

1. The reference builds with **no warnings**. Hawkmoth reports a directive that
   matches nothing, so this catches a symbol that was renamed or whose comment
   stopped being a doc comment.
2. Every public type is present. A list here would itself drift, so the
   expected set is read out of the header.
3. Internals stay out. Private members and the ``stage`` namespace are excluded
   by comment convention rather than by a filter, so the convention is worth
   testing: it is one careless ``/**`` away from leaking.

The build uses a minimal Sphinx config rather than ``docs/source/conf.py``, so
it does not need pyarrow or typedoc. CI's docs job builds the real one.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
HEADER = REPO / "cpp" / "ucis-xml" / "include" / "ucis_xml.hpp"
DOCS = REPO / "docs" / "source"

MINIMAL_CONF = '''
import os
project = "cpp-api-check"
extensions = ["hawkmoth"]
hawkmoth_root = {root!r}
hawkmoth_compiler = "g++"
hawkmoth_clang_cpp = ["-std=c++17"]
master_doc = "reference/cpp-api/index"
exclude_patterns = [
    "getting-started/**", "reference/python-api/**", "reference/typescript-api/**",
    "reference/backends/**", "reference/formats/**", "reference/c-api/**",
    "reference/index.rst", "reference/migration.rst", "index.rst",
    "_build/**", "patches/**",
]
html_theme = "basic"
nitpicky = False
'''


@pytest.fixture(scope="module")
def built(tmp_path_factory):
    pytest.importorskip("hawkmoth", reason="hawkmoth not installed")
    pytest.importorskip("sphinx", reason="sphinx not installed")

    conf_dir = tmp_path_factory.mktemp("conf")
    (conf_dir / "conf.py").write_text(
        MINIMAL_CONF.format(root=str(HEADER.parent)))
    out = tmp_path_factory.mktemp("out")

    proc = subprocess.run(
        [sys.executable, "-m", "sphinx", "-b", "text", "-E",
         "-c", str(conf_dir), str(DOCS), str(out)],
        capture_output=True, text=True)
    return proc, out


def test_reference_builds_without_warnings(built):
    proc, _ = built
    assert proc.returncode == 0, proc.stderr

    # "does not match documented symbols" is the one that means extraction
    # broke. The stray cross-reference to reference/c-api is expected: that
    # page is excluded from this cut-down build.
    noise = ("c-api/index",)
    warnings = [l for l in (proc.stderr + proc.stdout).splitlines()
                if ("WARNING" in l or "ERROR" in l)
                and not any(n in l for n in noise)]
    assert not warnings, "extraction produced warnings:\n" + "\n".join(warnings)


def public_types_in_header() -> set[str]:
    """Types declared in the header with a `/**` doc comment on them.

    Read from the source rather than listed here, so adding a public type
    cannot silently go undocumented.
    """
    text = HEADER.read_text()
    found = set()
    # A /** ... */ block immediately followed by a class/struct/enum-class.
    for m in re.finditer(
            r'/\*\*.*?\*/\s*\n\s*(?:class|struct|enum\s+class)\s+(\w+)',
            text, re.S):
        found.add(m.group(1))
    # Internals live in namespace stage and are commented with //, so anything
    # matching above is public by construction.
    return found


def test_every_publicly_documented_type_is_rendered(built):
    _, out = built
    page = (out / "reference" / "cpp-api" / "api.txt").read_text()

    expected = public_types_in_header()
    assert len(expected) >= 25, (
        f"only found {len(expected)} documented types in the header; the "
        f"scraper is probably broken rather than the docs")

    missing = sorted(t for t in expected if f"ucisxml::{t}" not in page)
    assert not missing, (
        "these types carry a /** comment in the header but do not appear in "
        f"the reference: {missing}")


def test_internals_stay_out_of_the_reference(built):
    _, out = built
    page = (out / "reference" / "cpp-api" / "api.txt").read_text()

    # A *declaration* of a stage symbol, not the string anywhere: the page's
    # own prose explains why the namespace is absent, which is not a leak.
    declared = re.findall(r'^(?:class|struct|enum class|\w[\w &*:]*)\s'
                          r'.*\bucisxml::stage::\w+', page, re.M)
    assert not declared, (
        "the staging namespace leaked into the public reference -- something "
        f"internal was given a /** comment: {declared[:5]}")

    # Trailing-underscore members are this codebase's private convention.
    leaked = sorted(set(re.findall(r'\b(\w+_)\b(?=\s*[;)])', page)))
    # Descriptor structs (Tool, Test, WriterOptions, Options, Point) expose
    # their fields publicly with that spelling, so they are expected.
    allowed = {
        "name_", "version_", "vendorId_", "category_", "passed_", "seed_",
        "cmd_", "args_", "cwd_", "userName_", "comment_", "physicalName_",
        "kind_", "timeunit_", "simTime_", "cpuTime_", "haveSimTime_",
        "haveCpuTime_", "sources_", "pretty_", "singleMember_",
        "stagingLimit_", "spoolThreshold_", "writtenTime_", "weight_",
        "goal_", "atLeast_", "autoBinMax_", "crossNumPrintMissing_",
        "detectOverlap_", "perInstance_", "mergeInstances_", "scope_",
        "module_", "file_", "line_", "signal_", "bit_", "edge_", "count_",
        "scopeFile_", "scopeLine_",
    }
    unexpected = [m for m in leaked if m not in allowed]
    assert not unexpected, f"private members leaked: {unexpected}"


def test_defaults_are_documented_in_prose(built):
    """Hawkmoth drops default arguments, so they must be stated in the text.

    Spot-checked rather than exhaustive: if the convention is being followed at
    all these will hold, and if someone stops following it the reference starts
    losing half the contract silently.
    """
    _, out = built
    page = (out / "reference" / "cpp-api" / "api.txt").read_text()

    # The signature genuinely has no "= 1" in it...
    assert "uint32_t inlineCount)" in page, (
        "hawkmoth started rendering default arguments -- the prose workaround "
        "can be revisited")
    # ...so the description has to say so.
    assert "Defaults to 1." in page
    assert 'Defaults to ``"if"``.' in page or "Defaults to" in page
    assert page.count("Defaults to") >= 30, (
        f"only {page.count('Defaults to')} documented defaults; the API has "
        f"far more defaulted parameters than that")
